export const USER_ROUTES = {
  dashboard: '/dashboard',
  login: '/login',
  register: '/register',
  notifications: '/notifications',
  profile: '/profile',
  teams: '/teams',
  teamsCreate: '/teams/create',
  invitationsInbox: '/invitations/inbox',
  wallet: '/wallet',
  walletRecharge: '/wallet/recharge',
  walletWithdraw: '/wallet/withdraw',
  walletHistory: '/wallet/history',
  walletGiftCardRedeem: '/wallet/gift-cards/redeem',
  subscriptions: '/subscriptions',
  products: '/products',
  orders: '/orders',
  myApps: '/my-apps',
  appRecharge: '/apps/recharge',
  appRechargeSuccess: '/apps/recharge/success',
  security: '/security',
  securityTwoFA: '/security/2fa',
  securityPasskey: '/security/passkey',
  securityLoginHistory: '/security/login-history',
  settings: '/settings',
  about: '/about',
  copyright: '/copyright'
} as const
